# This file was generated by nix4dev.
{
  description = "Tools to easily setup development environment.";

  # To change flake inputs, use the `nix4dev.projectFlake.inputs` option.
  inputs = {
    devshell = {
      inputs = {
        nixpkgs = {
          follows = "nixpkgs";
        };
      };
      url = "github:numtide/devshell";
    };
    flake-parts = {
      inputs = {
        nixpkgs-lib = {
          follows = "nixpkgs";
        };
      };
      url = "github:hercules-ci/flake-parts";
    };
    nixpkgs = {
      url = "github:NixOS/nixpkgs/nixos-25.11";
    };
    systems = {
      url = "github:nix-systems/default";
    };
    treefmt-nix = {
      inputs = {
        nixpkgs = {
          follows = "nixpkgs";
        };
      };
      url = "github:numtide/treefmt-nix";
    };
  };

  outputs =
    inputs:
    inputs.flake-parts.lib.mkFlake { inherit inputs; } {
      imports =
        let
          l = inputs.flake-parts.inputs.nixpkgs-lib.lib // builtins;
          assertFileExists =
            path: msg:
            assert (l.asserts.assertMsg (l.filesystem.pathIsRegularFile path) msg);
            path;
        in
        [
          ./flake-modules/templates.nix
          (assertFileExists ./flake-modules/default.nix ''
            Default flake module not found. To create an empty default module execute:

            mkdir -p ./flake-modules
            echo "{}" > ./flake-modules/default.nix

            in the directory containing the flake.nix file.
          '')
        ];
    };
}
