# This file was generated by nix4dev.
{
  description = "Tools to easily setup development environment.";

  # To change flake inputs, use the `nix4dev.projectFlake.extraInputs` option.
  inputs = {
    "devshell" = {
      "inputs" = {
        "flake-utils" = {
          "follows" = "flake-utils";
        };
        "nixpkgs" = {
          "follows" = "nixpkgs";
        };
      };
      "url" = "github:numtide/devshell";
    };
    "flake-parts" = {
      "inputs" = {
        "nixpkgs-lib" = {
          "follows" = "nixpkgs";
        };
      };
      "url" = "github:hercules-ci/flake-parts";
    };
    "flake-utils" = {
      "inputs" = {
        "systems" = {
          "follows" = "systems";
        };
      };
      "url" = "github:numtide/flake-utils";
    };
    "nixpkgs" = {
      "url" = "github:NixOS/nixpkgs/nixos-24.11";
    };
    "systems" = {
      "url" = "github:nix-systems/default";
    };
    "treefmt-nix" = {
      "inputs" = {
        "nixpkgs" = {
          "follows" = "nixpkgs";
        };
      };
      "url" = "github:numtide/treefmt-nix";
    };
  };

  outputs = inputs:
    inputs.flake-parts.lib.mkFlake
    {inherit inputs;}
    {
      imports = let
        l = inputs.nixpkgs.lib // builtins;
        assertFileExists = path: msg:
          assert (
            l.asserts.assertMsg
            (l.filesystem.pathIsRegularFile path)
            msg
          ); path;
      in [
        (
          assertFileExists
          ./flake-modules/default.nix
          ''
            Default flake module not found. To create an empty default module execute:

            mkdir -p ./flake-modules
            echo "{}" > ./flake-modules/default.nix

            in the directory containing the flake.nix file.
          ''
        )
      ];
    };
}
