# This file was generated by nix4dev.
{

  # To change flake inputs, use the `nix4dev.flake.inputs` option.
  inputs = {
    "dummy-flake" = {
      "url" = "github:jan-kouba/dummy-repo";
    };
    "flake-parts" = {
      "follows" = "nix4dev/flake-parts";
    };
    "nix4dev" = {
      "url" = "github:jan-kouba/nix4dev";
    };
  };

  outputs =
    inputs:
    inputs.flake-parts.lib.mkFlake { inherit inputs; } {
      imports =
        let
          l = inputs.flake-parts.inputs.nixpkgs-lib.lib // builtins;
          assertFileExists =
            path: msg:
            assert (l.asserts.assertMsg (l.filesystem.pathIsRegularFile path) msg);
            path;
        in
        [
          inputs.nix4dev.flakeModules.default
          inputs.dummy-flake.flakeModules.default
          (assertFileExists ./flake-modules/default.nix ''
            Default flake module not found. To create an empty default module execute:

            mkdir -p ./flake-modules
            echo "{}" > ./flake-modules/default.nix

            in the directory containing the flake.nix file.
          '')
        ];
    };
}
