# This file was generated by nix4dev.
{

  # To change flake inputs, use the `nix4dev.projectFlake.extraInputs` option.
  inputs = {
    "flake-parts" = {
      "inputs" = {
        "nixpkgs-lib" = {
          "follows" = "nixpkgs";
        };
      };
      "url" = "github:hercules-ci/flake-parts";
    };
    "nixpkgs" = {
      "url" = "github:NixOS/nixpkgs/nixos-25.05";
    };
  };

  outputs =
    inputs:
    inputs.flake-parts.lib.mkFlake { inherit inputs; } {
      imports =
        let
          l = inputs.nixpkgs.lib // builtins;
          assertFileExists =
            path: msg:
            assert (l.asserts.assertMsg (l.filesystem.pathIsRegularFile path) msg);
            path;
        in
        [
          ./flake-modules/seeds.nix
          (assertFileExists ./flake-modules/default.nix ''
            Default flake module not found. To create an empty default module execute:

            mkdir -p ./flake-modules
            echo "{}" > ./flake-modules/default.nix

            in the directory containing the flake.nix file.
          '')
        ];
    };
}
