jobs:
  nix4dev-check:
    if: github.event.pull_request.draft == false
    runs-on: ${{ matrix.runs-on}}
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Setup git for test
        run: |
          git config --global user.email "nix4dev-ci@github.com"
          git config --global user.name "nix4dev CI"
      - name: Run `check`
        run: |
          PRJ_ROOT="$(pwd)" nix run ./nix4dev#check
    strategy:
      matrix:
        runs-on:
          - ubuntu-22.04
          - macos-14
  nix4dev-test-all:
    if: github.event.pull_request.draft == false
    runs-on: ${{ matrix.runs-on}}
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Setup git for test
        run: |
          git config --global user.email "nix4dev-ci@github.com"
          git config --global user.name "nix4dev CI"
      - name: Run `test-all`
        run: |
          nix develop ./nix4dev -c test-all
    strategy:
      matrix:
        runs-on:
          - ubuntu-22.04
          - macos-14
name: nix4dev-check
"on":
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches:
      - master
  workflow_dispatch: {}
permissions:
  contents: read
  id-token: write
