{
  "jobs": {
    "nix4dev-check": {
      "runs-on": "${{ matrix.runs-on}}",
      "steps": [
        { "uses": "actions/checkout@v4" },
        {
          "name": "Install Nix",
          "uses": "DeterminateSystems/nix-installer-action@main"
        },
        {
          "name": "Setup Nix cache",
          "uses": "DeterminateSystems/magic-nix-cache-action@main"
        },
        {
          "name": "Setup git for test",
          "run": "git config --global user.email \"nix4dev-ci@github.com\"\ngit config --global user.name \"nix4dev CI\"\n"
        },
        { "name": "Run `check`", "run": "nix develop ./nix4dev -c check\n" }
      ],
      "strategy": { "matrix": { "runs-on": ["ubuntu-22.04", "macos-14"] } }
    },
    "nix4dev-test-all": {
      "runs-on": "${{ matrix.runs-on}}",
      "steps": [
        { "uses": "actions/checkout@v4" },
        {
          "name": "Install Nix",
          "uses": "DeterminateSystems/nix-installer-action@main"
        },
        {
          "name": "Setup Nix cache",
          "uses": "DeterminateSystems/magic-nix-cache-action@main"
        },
        {
          "name": "Setup git for test",
          "run": "git config --global user.email \"nix4dev-ci@github.com\"\ngit config --global user.name \"nix4dev CI\"\n"
        },
        {
          "name": "Run `test-all`",
          "run": "nix develop ./nix4dev -c test-all\n"
        }
      ],
      "strategy": { "matrix": { "runs-on": ["ubuntu-22.04", "macos-14"] } }
    }
  },
  "name": "nix4dev-check",
  "on": { "push": {}, "workflow_dispatch": {} },
  "permissions": { "contents": "read", "id-token": "write" }
}
